before_script:
  - sudo apt-get -y -q update
  - sudo apt-get -y -q install curl make libgc-dev binutils-dev zlib1g-dev libgc-dev

script:
  - export PATH=$PATH:$PWD/bin:$PWD/sam
  - export OOC_LIBS=$PWD
  - make rescue
  - make clean self
  - make clean self
  - make extensions
  - git clone --depth=1 git://github.com/nddrylliog/sam.git 
  - (cd sam && rock -v)
  - sam test rock.use

notifications:
  webhooks: http://rcmp.pw/freenode/ooc-lang

